name: flutter_utils
description: My custom utils used across many projects
version: 0.0.2
author: Rex Magana
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
