name: flutter_utils
description: My custom utils used across many projects
version: 0.0.2
author: Rex Magana
homepage:

environment:
  sdk: ">=2.11.0-213.0.dev <2.12.0"
  # sdk: ">=2.9.0-10.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
