name: flutter_utils
description: My custom utils used across many projects
version: 0.1.1
author: Rex Magana
homepage:

environment:
  sdk: ">=2.11.0-213.0.dev <2.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
